### ISSUE TITLE
Received message larger than max

### ISSUE THREAD

**Issue by postpuber** [QuokkaStake/cosmos-proposals-checker#97]
I've been getting this error regularly for Stargaze as of late. Any ideas?

> ❌ There was an error querying proposals on Stargaze mainnet.
> Error text: grpc: received message larger than max (16206870 vs. 10485760)

**Comment by freak12techno** [comment]
@postpuber hi, can you attach the app logs?

**Comment by freak12techno** [comment]
@postpuber okay, I figured. This shouldn't be the app's issue, but the node's one.
Can you update this part of your node's `app.toml` to set a somewhat bigger value and restart it?
```
[grpc]
...
# MaxRecvMsgSize defines the max message size in bytes the server can receive.
# The default value is 10MB.
max-recv-msg-size = "10485760"
```

**Comment by postpuber** [comment]
@freak12techno It helped. Thanks.

**Comment by freak12techno** [comment]
@postpuber glad that it worked!
